---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform

  vars:
    project_dir: /test1/work1

  tasks:

   - name: Basic deploy of an instance
     community.general.terraform:
      project_path: ./terraform_sn
      state: present
      force_init: true
