---
- amazon.aws.autoscaling_group:
    name: lauch
    availability_zones: [ 'us-east-1a', 'us-east-1b' ]
    launch_config_name: 'lc-1'
    min_size: 1
    max_size: 10
    desired_capacity: 5
    vpc_zone_identifier: [ 'subnet-05ded7de40b14c093', 'subnet-08958c4b1d3fb7539' ]
    tags:
      - environment: production
        propagate_at_launch: false

